### ISSUE TITLE
Check ELK license

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-elk#3]
ELK image license

1. opensource or free
2. redistribution

**Comment by chendelin1982** [comment]
refer to:
* [ELASTIC-LICENSE](https://github.com/elastic/elasticsearch/blob/master/licenses/ELASTIC-LICENSE-2.0.txt)
* [download](https://www.elastic.co/cn/downloads/elasticsearch)

**Comment by chendelin1982** [comment]
ES image include all features, you can set it by `xpack.license.self_generated.type`

* basic (default): to enable basic X-Pack features.
* trial: the self-generated license gives access
